// Core Module
const path = require('path');

// External Module
const express = require('express');
const session = require('express-session');
const MongoDBStore = require('connect-mongodb-session')(session);
const DB_PATH = "mongodb+srv://root:root@projects.gcju5uc.mongodb.net/airbnb?appName=projects";

//Local Module
const storeRouter = require("./routes/storeRouter")
const hostRouter = require("./routes/hostRouter")
const authRouter = require("./routes/authRouter")
const rootDir = require("./utils/pathUtil");
const errorsController = require("./controllers/errors");
const { default: mongoose } = require('mongoose');

const app = express();

app.set('view engine', 'ejs');
app.set('views', 'views');

//this store will save the session data in mongoDB we need to pass this store to session middleware
const store = new MongoDBStore({
  uri: DB_PATH,
  collection: 'sessions'
});

app.use(express.urlencoded({extended: false}));
//this session middleware will create session for each request if there is no session cookie
//secret is used to sign the cookie which will tell that cookie is generated by our server
//resave false means session will not be saved again if nothing is modified
//saveUninitialized true means session will be saved even if it is not initialized
//store is used to store the session data in mongoDB
app.use(session({
  secret: "KnowledgeGate AI with Complete Coding",
  resave: false,
  saveUninitialized: true,
  store
}));

//custom middleware to make isLoggedIn available in req object
//in this req.isLoggedin will confirm that user is logged in or not
//req.session is created by express-session middleware which contains the session data and from that we are getting isLoggedIn value
app.use((req, res, next) => {
  req.isLoggedIn = req.session.isLoggedIn
  next();
})


app.use(authRouter)
app.use(storeRouter);
app.use("/host", (req, res, next) => {
  //this statement is like if the user is logged in then call next middleware otherwise redirect to login page
  if (req.isLoggedIn) {
    next();
  } else {
    res.redirect("/login");
  }
});
app.use("/host", hostRouter);

app.use(express.static(path.join(rootDir, 'public')))

app.use(errorsController.pageNotFound);

const PORT = 3003;

mongoose.connect(DB_PATH).then(() => {
  console.log('Connected to Mongo');
  app.listen(PORT, () => {
    console.log(`Server running on address http://localhost:${PORT}`);
  });
}).catch(err => {
  console.log('Error while connecting to Mongo: ', err);
});

//in t this entire project it is like of the user will login as host or guest
//based on that userType we are showing different views and allowing different operations

//in signup validation we are checking that user is selecting userType and terms and conditions are accepted
//similarly while login we are checking that user is logging in as correct userType

//in host routes we are allowing access only if the user is logged in otherwise redirecting to login page

//similarly in views we are showing different navigation items based on userType and isLoggedIn status

//this is the updated signup validation code from authController.js

//signup validation array

//we are doing this validation in authController.js file wherewe will check that userType is either host or guest
//and terms and conditions checkbox is checked
/*
body('userType')
  .custom((value, { req }) => {
    if (value !== 'host' && value !== 'guest') {
      throw new Error('Invalid user type selected');
    }
    return true;
  }),
body('terms')
  .custom((value, { req }) => {
    if (!value) {
      throw new Error('You must accept the terms and conditions');
    }
    return true;
  } )
*/

//this is how we are checking in login post handler in authController.js
/*
const userType = req.body.userType;
if (user.userType !== userType) {
  return res.status(422).render('auth/login', {
    pageTitle: 'Login',       
    errorMessage: 'Invalid user type for this account.',
    oldInput: {
      email: email
    },
    validationErrors: []
  });
}
*/